<template>
  <main class="min-h-screen bg-stone-50 px-6 py-20">
    <div class="max-w-3xl mx-auto space-y-8">

      <router-link
          to="/about"
          class="text-sm text-slate-600 underline hover:text-slate-800"
      >
        ← Back to About
      </router-link>

      <h1 class="text-3xl font-semibold text-stone-800">
        Terms of Use
      </h1>

      <p class="leading-relaxed text-stone-700">
        MindWorks is a paid psychological reflection tool designed to support thoughtful self-reflection.
        It is not a diagnostic instrument, medical advice, or a substitute for professional assessment or treatment.
      </p>

      <p class="leading-relaxed text-stone-700">
        The reflections generated by MindWorks are based on self-reported information and structured language synthesis.
        Interpretation and use of this content is the responsibility of the user.
      </p>

      <p class="leading-relaxed text-stone-700">
        MindWorks is not intended for use in crisis situations, emergency decision-making,
        or where immediate professional support is required.
      </p>

      <p class="leading-relaxed text-stone-700">
        By using this service, you acknowledge and accept these limitations.
      </p>

    </div>
  </main>
</template>
